### ISSUE TITLE
missing libadwaita

### ISSUE THREAD

**Issue by renarena** [godehardt/glosung#3]
I am using LinuxMint Debian Edition (bullseye). 
The .deb version cannot be installed du to missing libadwaita-1-0.

**Comment by godehardt** [comment]
libadwaita is part of gtk4.  Both are not available for bullseye.  Sorry for that.
But glosung 3.6.6 should work.

**Comment by renarena** [comment]
on 3.6.6. the icon is black on dark ground :-(

**Comment by godehardt** [comment]
Both issues should be fixed now in version 4.1

**Comment by renarena** [comment]
the icon is still black on dark ground in dark designs
